
update_transactive_home:
  description: Update values in transactive home 

  fields:
    obj:
      description: An object containing the value
      example: 'obj.value'

update_transactive_home_device:
  description: Update a transactive home device 

  fields:
    device:
      description: Name of device to change
      example: 'device1'

    obj:
      description: An object containing the value
      example: 'obj.value'